# Puerto independiente para el microservicio de Identidad
server.port=8083

# Conexión a la base de datos (Usaremos la misma que ms-auth)
spring.datasource.url=jdbc:postgresql://localhost:5432/sanosysalvosDB
spring.datasource.username=postgres
spring.datasource.password=admin

# Configuración de Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect