# La URL apunta a tu base de datos (sanosysalvosDB)
spring.datasource.url=jdbc:postgresql://localhost:5432/sanosysalvosDB

# El usuario es postgres
spring.datasource.username=postgres

# Tu contraseña real de pgAdmin
spring.datasource.password=admin

# Drivers y configuración de Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect